import time
from unittest.mock import MagicMock
from src.services.platform_rate_limiter import PlatformRateLimiter

def test_rate_limiter_before_request_allows_by_default():
    config = {
        "pchome": {"min_delay_seconds": 0}
    }
    db = MagicMock()
    # Mock source_health to return empty
    db.get_source_health.return_value = []
    
    limiter = PlatformRateLimiter(config, db)
    # Should allow immediately
    assert limiter.before_request("pchome") is True

def test_rate_limiter_before_request_checks_cooldown():
    config = {}
    db = MagicMock()
    # Mock a record in cooldown
    record = MagicMock()
    record.platform = "pchome"
    record.source_name = "direct_html"
    record.enabled = True
    record.cooldown_until = "2099-01-01T00:00:00+00:00"
    db.get_source_health.return_value = [record]
    
    limiter = PlatformRateLimiter(config, db)
    # Should deny because it's in cooldown
    assert limiter.before_request("pchome") is False

def test_rate_limiter_on_429_triggers_cooldown():
    config = {
        "pchome": {"cooldown_after_429_minutes": 90}
    }
    db = MagicMock()
    db.get_source_health.return_value = []
    
    limiter = PlatformRateLimiter(config, db)
    limiter.on_429("pchome", "direct_html")
    
    # It should upsert into source_health
    assert db.upsert_source_health.called
    kwargs = db.upsert_source_health.call_args[1]
    assert kwargs["source_name"] == "direct_html"
    assert kwargs["platform"] == "pchome"
    assert kwargs["cooldown_until"] is not None

def test_rate_limiter_pchome_escalation():
    config = {
        "pchome": {"cooldown_after_429_minutes": 90}
    }
    db = MagicMock()
    record = MagicMock()
    record.platform = "pchome"
    record.source_name = "direct_html"
    record.rate_limited_count_24h = 2 # already 2 limits today
    db.get_source_health.return_value = [record]
    
    limiter = PlatformRateLimiter(config, db)
    limiter.on_429("pchome", "direct_html")
    
    # Escalation to 360 mins (6 hours)
    # Cooldown time generated by trigger_cooldown
    assert db.upsert_source_health.called
